services:
  temperature:
    image: brojohn/apache:1.1
    container_name: temperature
    hostname: locahost
    volumes:
      - ./public:/var/www/html
    restart: always
    ports:
      - 8082:80
    working_dir: /var/www/html
    networks:
      - transfashion

networks:
  transfashion:
    external: true
